name: Deploy Static Website to Azure Storage

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web-site/**'
      - '.github/workflows/deploy-static.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Azure CLI
        uses: azure/cli@v2

      - name: Upload to $web
        run: |
          az storage blob upload-batch \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --account-key "$AZURE_STORAGE_KEY" \
            --destination '$web' \
            --source web-site \
            --overwrite
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY:     ${{ secrets.AZURE_STORAGE_KEY }}
